
env:
  RESOURCE_GROUP_LOCATION: 'EastUS2'
  RESOURCE_GROUP_NAME: 'crc-azure-resource-group-00'
  TEMPLATE_FILE_NAME: 'function-template.json'  

name: Deploy Arm Templates

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-arm-resources:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
          echo "Azure resource group created"
    - uses: azure/arm-deploy@v1
      with:
        scope: 'resourcegroup'
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./${{ env.TEMPLATE_FILE_NAME }}
        parameters: COSMOSDB_CONNECTION_STRING=${{ secrets.COSMOSDB_CONNECTION_STRING }} COSMOS_TABLE_NAME=${{ secrets.COSMOS_TABLE_NAME }} COSMOS_DB_NAME=${{ secrets.COSMOS_DB_NAME }}
